Resources:
  RecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNameRecipes}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: recipeId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: recipeId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  PlaylistsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNamePlaylists}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: playlistId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: playlistId
          KeyType: RANGE

      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}


  UserTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNameUserTokens}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: provider
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: provider
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

